# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Myntra Engineering
tagline:             Stories of code.
url:                 http://myntra.github.io
paginate:            10
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/poole/poole

# Authors
authors:
  sunilpai:
    display_name: Sunil Pai
    gravatar: 6eadce66e218b83b484c5e1ee293f5b9
    email: 
    web: 
    twitter: threepointone
    github: threepointone
  paramaggarwal:
    display_name: Param Aggarwal
    gravatar: c09fc4869aa6e7a5da24079ec0e04f9a
    email: 
    web: 
    twitter: paramaggarwal
    github: paramaggarwal		